version: '3.8'

services:
  app:
    build: .
    container_name: compro_assets_app
    ports:
      - '8000:8000'
    environment:
      # Application
      APP_NAME: ${APP_NAME:-compro_assets}
      APP_VERSION: ${APP_VERSION:-1.0.0}
      DEBUG: ${DEBUG:-true}

      # Database
      DATABASE_URL: ${DATABASE_URL}

      # Atlas SSO
      ATLAS_SSO_URL: ${ATLAS_SSO_URL}
      ATLAS_APP_CODE: ${ATLAS_APP_CODE:-COMPRO_ASSETS}
      ATLAS_ENCRYPTION_KEY: ${ATLAS_ENCRYPTION_KEY}
      ATLAS_ENCRYPTION_IV: ${ATLAS_ENCRYPTION_IV}

      # Response Encryption
      ENCRYPTION_ENABLED: ${ENCRYPTION_ENABLED:-false}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      ENCRYPTION_IV: ${ENCRYPTION_IV}

      # Logging
      LOGGING_ENABLED: ${LOGGING_ENABLED:-true}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      LOG_TO_FILE: ${LOG_TO_FILE:-false}

      # CORS
      CORS_ORIGINS: ${CORS_ORIGINS}
      CORS_ALLOW_CREDENTIALS: ${CORS_ALLOW_CREDENTIALS:-true}
      CORS_ALLOW_METHODS: ${CORS_ALLOW_METHODS}
      CORS_ALLOW_HEADERS: ${CORS_ALLOW_HEADERS}

      # Rate Limiting
      RATE_LIMIT_ENABLED: ${RATE_LIMIT_ENABLED:-true}
      RATE_LIMIT_REQUESTS: ${RATE_LIMIT_REQUESTS:-100}
      RATE_LIMIT_WINDOW: ${RATE_LIMIT_WINDOW:-60}

    networks:
      - compro_assets_network

    restart: unless-stopped

networks:
  compro_assets_network:
    driver: bridge
